language: scala

dist: trusty

sudo: required

services:
  - docker

scala:
  - 2.11.8

jdk:
  - oraclejdk8

addons:
  postgresql: "9.5"

cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2

notifications:
  slack:
    secure: m77P/oPazWaem1QdYeCE3Qs/lSS1T4KGpX8g8VCHwABff09QWzTzHXEnYHnDNNDnwWJWC+CWIlfEIFcgUQDVBFYETSJ44HzopZBm2WJRTCMessaMBvALLqUyXprGxgrKcvBDPOWGP3fIeGBKAIdC/AiB82AJ7kXZWnoWrUwokdsrgwL4FzxjqnXuTAG1+mltdXcB3WVle7KqpeCOmJo5Kwg3dwDcJamcElyxIcJId2Lwg70NKNSLNupv3M2i2/GE8s6p2pVuPfynIJVmyYSBXUboQ4Y/zsL3iTHmsLD38L4avz4bvcHLPm7Lb0fUI0prwBEftjpiEZYNNSczLk1XfffFSrfAhmgT9HGmO4ra4Eeps4vsuaFAFD8CHjhnohg2Gp77Xzc43FTh3pmxDeb+K34a+yncGljFuneCF0vZRZQ5R7it/fsUBtNhYnwwS88GCG1L9ZyUKE2qwYVSwq4TyEHnTMvdxCeNzYV/Mnw+FjpvGO9uLCtVvvdZP4Tt+YqajPT+XgtcDPvoWb8MO2CoyMCnvFEU4nT87ks7hwxT+Hv5SsPU/XZdgm6ahelpwWWoNaMgs0nYRdVeV3kPEP3GSKeD/hOd/5UhFa7r9u5Ir9ZhjMrEi6eUgoOk8TMdXNHtTgxzO4AxVnrelCIbJQ4SH8LGqOLVJHWTF0mLVxcsBzE=
    on_success: always # default: always
    on_failure: change # default: always

branches:
  only:
    - master
    - testing
    - dev

# Handle git submodules yourself
git:
    submodules: false

env:
  global:
    - RUMPEL_BUCKET=rumpel-build-artifacts
    - AWS_DEFAULT_REGION=eu-west-1
    - secure: rGkp2QHhU+T5VvIRYALgwCPkUqP64vZjVaUgmqt2B53N1hxLuJs3FMc9qdd3+0SJTTFndGSsGjANE6Nb6FZeEoT1OB8TQvW9ZOGZCbggpZLFfAEudZo4lzLBR0PASa7nJyyvlVaxuay7g6K0Llqm1Lfphd/1FAW6bmDORwJIbikak7ejfwAWoZCrzp5xmTsC7OZ6Th1dJ5HLCZhionPQ8jp1nEedrbC4a4ryop9D7vlF+zu7vxTd/ZHC41mKGUdrfCyzkWGhK58Ne1dNdHYiP/Arj30m0s36alkPsXeZnnfbWYqy+6u9KkR0Rt+cIgJALkIYY/aQQIqvREsaN4hcYn6DP02J8Yw0GUDDV+Mu1V+kCdWHI6izoJZjlGmZ6uXbABXbEiYFlp2j+JEa89B1diEL8sQ7qFShUs1/cUOGg1XYEyZq4ht8peIGhoTADHNFO+mSt6R8jxZThzD5YXJ7miAMvXCwENNEEZZQ32K7Ar2IREa99FLTpSSduQHz6TH8upZMICFHXwdM/Z2P72jELQ/cRBT3WkHGUm5pncOklu/zb1D7quvSm2sd97hVKczTxHM74XdBVhWEGEPpj+bzRhzKISDYlwDngCO08fv5HefqSbgewk0Ks+HhYb7aHOlmk5B568rymGD2VQJIGRD+Acyp1PrEyBNcVyfYtYAMHKw=
    - secure: mXXvzrn94Nb6YWEskkdidDisSb2ncIX+8fnfBC7Z2zwgITHCa2kHva54fs8qMH5CAFTm6ROx+l3ejbYvUWiHQeLMefzXrnTicB7XAfYKkOfM2V5jmuweNFkn+AozZOos5vPfcuribrlHck57C9LcpkhkZARgNKaWskLFSTmwWjFRiaf0tqFm+8kaa01obu4SQLaYmyfmyUDVJga3L9HiZ8VybeaP3rYp0Z1vpX5+foqRmwFSHpcKiIrBjBzqMm/Tkf6R9gceXsCaZVmlfmyCuKxFos0Js0EwYX+xaduVKZU8xSwQ1p9m/r69qAlFQ2/Nd1iIYasTE1VY7O/FAIUz0N8S0R6SL0D5TwqNvS6lhUjPpn+vI3co5EvMtiVJ9E2ebBkKTvNJ1131rIwecIqUStDvCCFLMwuHDsSwtiAj/mTiuggK0dS4GGYFrTx5qxHR+9SUSGHIezgqEXXU3Ok9FPVRTNOxV97AMOQciXictroSX2Arpdho677/rpIkPnhJmxbUMe5x+TxnvyUdbMF3eDV22RlnJEp7wM12FrwVOUAYYDvpAg6RhCo3maV8e27en+DYWmP/oQaVnwWCkgYjKl+SdrNZf85gDdsPbU8yrVdNlpAeKfc6YgFSXdkyC06ma1t7BPgsyv7O25i0VgoFBbkhTQ/M2P599o0cGKuY8l4=
    - secure: USVpIy0emFH9ZvrkckuOxF3a9SsWOnH5a8XqZ/5WcA8xT+Jk3MDk8f1upx4DBpa4V4DRxI7Cvr326cP/Xi2gsBmgaKneo1tjACExIy42R9YZ8XPdr1Bbng7LDO4xfNSrKwMBUOeA1vF9/yZU4ki0Fv/J5wLYCthpnfEQ7+mubZ9h4dzFv0hd1wAinFR0vTVAn3+dQ4jaZSU9Tl/0L5T7y2Z2v/m9c4PHkII38WwdIvkrdY2jmSm0eSD7iEIwv3UwYk9BTIknmdHYfQ7xx256tRkadgMThmhdJhdm6JaLr819fXe30u/OIH15hLyM4ND+FjW6DvKNs3+2AVT7uOSK/wRntA2Fwvpczq7cwMxi2mU4HXXzH7a82Iswnm8Nn6Od+9vxsRV3nyl8XLmkn8Gn03k6+Pr2jj/ljdvGYeFmMYcvSlskE6VbWBGxyu6vAjccnUtGK9r3lkoxjX8CgiCev+/fwX5jlWvTSVeS8bvGy7dlRQQ2XRscQ8av5fKcACZOJVpQ4YgKnQ8j4MDUfT6sJ/8kONwXu4d6f9AREazZEml5taKvkZuDpHWPr77SqG+9Fccybm8IWjr0uq1eR+URsKJAXWj7ah0a7qA4M8WikH0FePR79YyyF2APm8KtDe7ZsbkbMdjVngrRhpACCUtsGLPhX4Y62szoBY8SzYJV/LI=
    - secure: garvO7sZMrDyhJ/LroK5SlidZCCBRa868Ebmuwwv75vlqeablbQk0LKEFqk6WjO428TIsu+JT0fkrg8eVoJPYO1n6/GhjtI9R4TgRNWcsoaFZe1RdCJkZoJemaeXkDomq34ZKRwnl7QsWeKInqtwDl3EJwoALaQjPPXEsrO20uodLKD8zFhCf89uQ4HIW6kAXJHTQSXByjkuRenhnyQ4nM/ixLnHZ+auJ/NG2RFUPADxRjpTNWcKoqvVh7QGzvYCiahDSaY669bZnLmTzOMH1EtVf8UPDFyHM56Pgq3a/OdOU4sxhSIdf3C+pbD8XV4lmU3gE/OLbybkk87YsU4J5iZLr552Dkm+g0ak2AnF4lxQwzm0sN/Q76eZRGpcBacncCLRlLK1kmWlfoJ6RrQTPRMBmNIzveCZ9gSY49AWEMUSn7ZG9F+MxCYnVAWlWDAEhKfQLYpHACa/GbGgvBaek6wG8vaeTMeBEVunpb3lsgQJ7fNBVtQ4vcn++0be1kW3+bAmPlviDJ+myey2O2uk1f5/T3k0s7UhbFcTzfN7HJ+2eIpg1Hp0FbmVEJvZVmE6TE8tiF0UwAJzbKDeU2HwGg8dXBbpKn/GWm70R1yytOCls4Mmndfxq75tnh9/ZRK7ihpa+TDg/xAjWqREGo1nHhObmY5L3rWxptyWKPgdVeA=
  matrix:
#    - REPOSITORY_NAME=hubofallthings RUMPEL=hubofallthings
#    - REPOSITORY_NAME=hubat RUMPEL=hubat
    - REPOSITORY_NAME=xtiva RUMPEL=xtiva

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

before_script:
  - psql -c "CREATE DATABASE testhatdb1;" -U postgres
  - psql -c "CREATE USER testhatdb1 WITH PASSWORD 'testing';" -U postgres
  - psql -c "GRANT CREATE ON DATABASE testhatdb1 TO testhatdb1" -U postgres
  - cd ./hat/app/org/hatdex/hat/phata/assets/
  - aws s3 cp s3://${RUMPEL_BUCKET}/${RUMPEL} rumpel --recursive
  - cp rumpel/*.js* js/
  - gzip --keep --force js/*.bundle.js
  - cp -r rumpel/assets .
  - rm -r rumpel
  - cd -

script:
  - sbt clean
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile
  - sbt coverage "testOnly org.hatdex.hat.api.*" -Dconfig.file=src/main/resources/application.test.conf
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt "project hat" docker:stage
  - cd hat/target/docker/stage && docker build -t ${REPOSITORY_NAME}/hat:${TRAVIS_COMMIT} . && cd -

after_success:
  - sbt coveralls

deploy:
  - provider: script
    script:
      - export AWS_SECRET_ACCESS_KEY=${DEPLOY_AWS_SECRET_ACCESS_KEY}
      - export AWS_ACCESS_KEY_ID=${DEPLOY_AWS_ACCESS_KEY_ID}
      - ECR_REPOSITORY=$(aws ecr describe-repositories --repository-name ${REPOSITORY_NAME} --query 'repositories[0].repositoryUri' --output text)
      - eval $(aws ecr get-login --no-include-email)
      - docker tag ${REPOSITORY_NAME}/hat:${TRAVIS_COMMIT} ${ECR_REPOSITORY}:${TRAVIS_COMMIT}
      - docker push ${ECR_REPOSITORY}:${TRAVIS_COMMIT}
    on:
      repo: Hub-of-all-Things/HAT2.0
      branch: dev